
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;
//importaciones
import Actividades.CrearActividad;
import Comida.CrearComida;
import ContMascota.controlaMascota;
import Mascota.mascota;
import Medicina.medicina;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;

/**
 *
 * @author User
 */
public class FrmTamagochi extends javax.swing.JFrame {

    private controlaMascota controlador;// declaramos atributo controlador
    //se instancia el constructor ubicado en el factory de comidas para enviar los valores por parametro
    CrearComida comida = new CrearComida(); 
    //intancia de constructor ubicado en el factory de actividades para enviar por parametro los valores 
    CrearActividad actividad = new CrearActividad();
 
    //metodos get que se utilizan en el controlaMascota
    public ButtonGroup getACCIONESMASCOTA() {
        return ACCIONESMASCOTA;
    }

    public JLabel getLMASCOTA() {
        return lblMascota;
    }

    public JProgressBar getBABURRIMIENTO() {
        return JbAburrimiento;
    }

    public JProgressBar getBBAÑO() {
        return JbBaño;
    }

    public JProgressBar getBENERGIA() {
        return JbEnergia;
    }

    public JProgressBar getBHAMBRE() {
        return JbHambre;
    }

    public JLabel getLEDAD() {
        return lblEdad;
    }

    public JLabel getLNOMBRE() {
        return lblNombre;
    }

    /**
     * Creates new form FrmTamagochi
     */
    public FrmTamagochi() {
        initComponents();
        // ajusta la posicion del frame
        this.setLocationRelativeTo(null);
        //instancia de una mascota creandola e iniciandola y se recibe el nombre en JOptionPAne
        this.controlador = new controlaMascota(new mascota(JOptionPane.showInputDialog(this, 
                "Ingrese un nombre a su mascota", "Mascota", 1)), this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ACCIONESMASCOTA = new javax.swing.ButtonGroup();
        lblMascota = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Energia = new javax.swing.JLabel();
        Hambre = new javax.swing.JLabel();
        JbEnergia = new javax.swing.JProgressBar();
        JbHambre = new javax.swing.JProgressBar();
        Aburrimiento = new javax.swing.JLabel();
        JbAburrimiento = new javax.swing.JProgressBar();
        Baño = new javax.swing.JLabel();
        JbBaño = new javax.swing.JProgressBar();
        Nombre = new javax.swing.JLabel();
        Edad = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JmCorrer = new javax.swing.JMenuItem();
        JmEscarbar = new javax.swing.JMenuItem();
        JMNadar = new javax.swing.JMenuItem();
        JMCazar = new javax.swing.JMenuItem();
        JMZorritas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JmPaloma = new javax.swing.JMenuItem();
        JmManzana = new javax.swing.JMenuItem();
        JmNuez = new javax.swing.JMenuItem();
        JmConejo = new javax.swing.JMenuItem();
        JmRaton = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        JMCuracion = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        JMBaño = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        JMDormir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tamagochi");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMascota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Huevo3.png"))); // NOI18N
        lblMascota.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 580, 470));
        lblMascota.getAccessibleContext().setAccessibleName("LMASCOTA");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Energia.setBackground(new java.awt.Color(255, 255, 255));
        Energia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Energia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Energia.setText("ENERGIA");
        Energia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Hambre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Hambre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hambre.setText("HAMBRE");
        Hambre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JbEnergia.setBackground(new java.awt.Color(255, 153, 51));
        JbEnergia.setStringPainted(true);

        JbHambre.setBackground(new java.awt.Color(255, 153, 51));
        JbHambre.setStringPainted(true);

        Aburrimiento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Aburrimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Aburrimiento.setText("ABURRIMIENTO");
        Aburrimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JbAburrimiento.setBackground(new java.awt.Color(255, 153, 51));
        JbAburrimiento.setForeground(new java.awt.Color(0, 0, 0));
        JbAburrimiento.setStringPainted(true);

        Baño.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Baño.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Baño.setText("BAÑO");
        Baño.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JbBaño.setBackground(new java.awt.Color(255, 153, 51));
        JbBaño.setStringPainted(true);

        Nombre.setBackground(new java.awt.Color(102, 102, 255));
        Nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setText("NOMBRE");
        Nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Edad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Edad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Edad.setText("EDAD");
        Edad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblEdad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEdad.setText("0");

        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hambre, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JbHambre, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(Energia, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JbEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Aburrimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JbAburrimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Baño, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JbBaño, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Energia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JbEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Aburrimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JbAburrimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Hambre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JbHambre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Baño, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JbBaño, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Edad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        JbEnergia.getAccessibleContext().setAccessibleName("BENERGIA");
        JbHambre.getAccessibleContext().setAccessibleName("BHAMBRE");
        JbAburrimiento.getAccessibleContext().setAccessibleName("BABURRIMIENTO");
        JbBaño.getAccessibleContext().setAccessibleName("BBAÑO");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 100));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/paisaje.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 660));

        jMenu1.setText("Actividad");
        ACCIONESMASCOTA.add(jMenu1);
        jMenu1.setEnabled(false);

        JmCorrer.setText("Correr");
        JmCorrer.setToolTipText(" -40 de energia, aburrimiento -20");
        JmCorrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmCorrerActionPerformed(evt);
            }
        });
        jMenu1.add(JmCorrer);

        JmEscarbar.setText("Escarbar");
        JmEscarbar.setToolTipText("-30 de enrgia, -20 de aburrimiento");
        JmEscarbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmEscarbarActionPerformed(evt);
            }
        });
        jMenu1.add(JmEscarbar);

        JMNadar.setText("Nadar");
        JMNadar.setToolTipText("-20 de energia, -10 de aburrimiento");
        JMNadar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMNadarActionPerformed(evt);
            }
        });
        jMenu1.add(JMNadar);

        JMCazar.setText("Cazar");
        JMCazar.setToolTipText("-20 de energia, -30 de aburrimiento");
        JMCazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMCazarActionPerformed(evt);
            }
        });
        jMenu1.add(JMCazar);

        JMZorritas.setText("Buscar Zorritas");
        JMZorritas.setToolTipText("-50 de energia, -20 de aburrimiento");
        JMZorritas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMZorritasActionPerformed(evt);
            }
        });
        jMenu1.add(JMZorritas);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Alimentar");
        ACCIONESMASCOTA.add(jMenu2);
        jMenu2.setEnabled(false);

        JmPaloma.setText("Paloma");
        JmPaloma.setToolTipText("+20 de enrgia, -20 de hambre, 10min");
        JmPaloma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmPalomaActionPerformed(evt);
            }
        });
        jMenu2.add(JmPaloma);

        JmManzana.setText("Manzana");
        JmManzana.setToolTipText("+10 de energia, -10 de hambre, 2 min");
        JmManzana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmManzanaActionPerformed(evt);
            }
        });
        jMenu2.add(JmManzana);

        JmNuez.setText("Nuez");
        JmNuez.setToolTipText("+10 de energia, -10 de hambre, 2min");
        JmNuez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmNuezActionPerformed(evt);
            }
        });
        jMenu2.add(JmNuez);

        JmConejo.setText("Conejo");
        JmConejo.setToolTipText("+30 de energia, -10 de hambre, 1min");
        JmConejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmConejoActionPerformed(evt);
            }
        });
        jMenu2.add(JmConejo);

        JmRaton.setText("Raton");
        JmRaton.setToolTipText("+15 de energia, -12 de hambre, 7min");
        JmRaton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmRatonActionPerformed(evt);
            }
        });
        jMenu2.add(JmRaton);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Curar");
        jMenu4.setToolTipText("Cambia del estado enfermo al estado saludable");
        ACCIONESMASCOTA.add(jMenu4);
        jMenu4.setEnabled(false);

        JMCuracion.setText("Curacion");
        JMCuracion.setToolTipText("Sirve para pasar de enfermo a saludable");
        JMCuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMCuracionActionPerformed(evt);
            }
        });
        jMenu4.add(JMCuracion);

        jMenuBar1.add(jMenu4);
        jMenu4.getAccessibleContext().setAccessibleDescription("Curacion Total");

        jMenu5.setText("Baño");
        jMenu5.setToolTipText("Reduce las ganas de ir al baño -30");
        ACCIONESMASCOTA.add(jMenu5);
        jMenu5.setEnabled(false);

        JMBaño.setText("Baño");
        JMBaño.setToolTipText("-30 de baño");
        JMBaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMBañoActionPerformed(evt);
            }
        });
        jMenu5.add(JMBaño);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("Dormir");
        ACCIONESMASCOTA.add(jMenu3);
        jMenu3.setEnabled(false);

        JMDormir.setText("Dormir");
        JMDormir.setToolTipText("+100 de energia, +20 de hambre, + 40 de baño");
        JMDormir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMDormirActionPerformed(evt);
            }
        });
        jMenu3.add(JMDormir);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMNadarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMNadarActionPerformed
        //Interfaz de actividades nombre,energia,aburrimiento
        this.controlador.actividad(actividad.crear("Nadar", 20, 10));//llenado del constructor fabricar alojado en el Interfaz
    }//GEN-LAST:event_JMNadarActionPerformed

    private void JMBañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMBañoActionPerformed
        // TODO add your handling code here:
        this.controlador.Baño();// llamando del metodo ir al baño y resta -30 de baño
    }//GEN-LAST:event_JMBañoActionPerformed

    private void JmConejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmConejoActionPerformed
        // TODO add your handling code here:
        this.controlador.comer(comida.crear(30, 10, 3, "Conejo"), JmConejo);
    }//GEN-LAST:event_JmConejoActionPerformed

    private void JmCorrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmCorrerActionPerformed
        // TODO add your handling code here:

        this.controlador.actividad(actividad.crear("Escarbar", 40, 20));
    }//GEN-LAST:event_JmCorrerActionPerformed

    private void JmPalomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmPalomaActionPerformed
        // TODO add your handling code here:
        this.controlador.comer(comida.crear(20, 20, 3, "Paloma"), JmPaloma);
    }//GEN-LAST:event_JmPalomaActionPerformed

    private void JmManzanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmManzanaActionPerformed
        // TODO add your handling code here:
        this.controlador.comer(comida.crear(10, 20, 1, "Manzana"), JmManzana);
    }//GEN-LAST:event_JmManzanaActionPerformed

    private void JmNuezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmNuezActionPerformed
        // TODO add your handling code here:
        this.controlador.comer(comida.crear(10, 10, 1, "Nuez"), JmNuez);
    }//GEN-LAST:event_JmNuezActionPerformed

    private void JmRatonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmRatonActionPerformed
        // TODO add your handling code here:
        this.controlador.comer(comida.crear(15, 12, 2, "Raton"), JmRaton);
    }//GEN-LAST:event_JmRatonActionPerformed

    private void JmEscarbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmEscarbarActionPerformed
        // TODO add your handling code here:
        this.controlador.actividad(actividad.crear("Correr", 30, 10));
    }//GEN-LAST:event_JmEscarbarActionPerformed

    private void JMCazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMCazarActionPerformed
        // TODO add your handling code here:
        this.controlador.actividad(actividad.crear("Cazar", 20, 20));
    }//GEN-LAST:event_JMCazarActionPerformed

    private void JMZorritasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMZorritasActionPerformed
        // TODO add your handling code here:
        this.controlador.actividad(actividad.crear("Buscar Zorritas", 50, 20));
    }//GEN-LAST:event_JMZorritasActionPerformed

    private void JMCuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMCuracionActionPerformed
       //se le agrega un tiempo largo de recuperacion ya que este objeto recupera de criticos ejemplo si energia llega a -10 le sube 20
        this.controlador.tomarMedicina(new medicina("Curacion", 1440), JMCuracion);
    }//GEN-LAST:event_JMCuracionActionPerformed

    private void JMDormirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMDormirActionPerformed
      //se llama al metodo dormir que recupera 100 de energia y 40 baño 
        this.controlador.dormir();// 
    }//GEN-LAST:event_JMDormirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTamagochi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTamagochi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTamagochi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTamagochi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTamagochi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ACCIONESMASCOTA;
    private javax.swing.JLabel Aburrimiento;
    private javax.swing.JLabel Baño;
    private javax.swing.JLabel Edad;
    private javax.swing.JLabel Energia;
    private javax.swing.JLabel Hambre;
    private javax.swing.JMenuItem JMBaño;
    private javax.swing.JMenuItem JMCazar;
    private javax.swing.JMenuItem JMCuracion;
    private javax.swing.JMenuItem JMDormir;
    private javax.swing.JMenuItem JMNadar;
    private javax.swing.JMenuItem JMZorritas;
    private javax.swing.JProgressBar JbAburrimiento;
    private javax.swing.JProgressBar JbBaño;
    private javax.swing.JProgressBar JbEnergia;
    private javax.swing.JProgressBar JbHambre;
    private javax.swing.JMenuItem JmConejo;
    private javax.swing.JMenuItem JmCorrer;
    private javax.swing.JMenuItem JmEscarbar;
    private javax.swing.JMenuItem JmManzana;
    private javax.swing.JMenuItem JmNuez;
    private javax.swing.JMenuItem JmPaloma;
    private javax.swing.JMenuItem JmRaton;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblMascota;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
